/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul10;

/**
 *
 * @author Administrator
 */
public class latihan extends javax.swing.JFrame {
    

    /**
     * Creates new form latihan
     */
    public latihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        eHasil = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        meItBersih = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        hitung = new javax.swing.JMenu();
        meItKali = new javax.swing.JMenuItem();
        meItBagi = new javax.swing.JMenuItem();
        meItTambah = new javax.swing.JMenuItem();
        meItKurang = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuPersegiPanjang = new javax.swing.JMenuItem();
        jMenuSegitiga = new javax.swing.JMenuItem();
        jMenuLingkaran = new javax.swing.JMenuItem();
        menBantuan = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Data 1");

        jLabel3.setText("Data 2");

        jLabel4.setText("Hasil");

        menFile.setText("File");
        jMenuBar1.add(menFile);

        meItBersih.setText("Proses");

        jMenuItem1.setText("Bersih");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        meItBersih.add(jMenuItem1);

        hitung.setText("Hitung");

        meItKali.setText("Kali");
        meItKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItKaliActionPerformed(evt);
            }
        });
        hitung.add(meItKali);

        meItBagi.setText("Bagi");
        meItBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItBagiActionPerformed(evt);
            }
        });
        hitung.add(meItBagi);

        meItTambah.setText("Tambah");
        meItTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItTambahActionPerformed(evt);
            }
        });
        hitung.add(meItTambah);

        meItKurang.setText("Kurang");
        meItKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meItKurangActionPerformed(evt);
            }
        });
        hitung.add(meItKurang);

        meItBersih.add(hitung);

        jMenu1.setText("Hitung Bentuk");

        jMenuPersegiPanjang.setText("Persegi Panjang");
        jMenuPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPersegiPanjangActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPersegiPanjang);

        jMenuSegitiga.setText("Segitiga");
        jMenuSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSegitigaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSegitiga);

        jMenuLingkaran.setText("Lingkaran");
        jMenuLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLingkaranActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuLingkaran);

        meItBersih.add(jMenu1);

        jMenuBar1.add(meItBersih);

        menBantuan.setText("Bantuan");
        jMenuBar1.add(menBantuan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eHasil))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eData2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void meItKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItKaliActionPerformed
int Data1 = Integer.parseInt(eData1.getText()); 
int Data2 = Integer.parseInt(eData2.getText()); 
int Hasil; 
Hasil = Data1*Data2; 
eHasil.setText(String.valueOf(Hasil));        // TODO add your handling code here:
    }//GEN-LAST:event_meItKaliActionPerformed

    private void meItBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItBagiActionPerformed
int Data1 = Integer.parseInt(eData1.getText());  
int Data2 = Integer.parseInt(eData2.getText());  
int Hasil; 
Hasil = Data1/Data2;  // Operasi pembagian
eHasil.setText(String.valueOf(Hasil));
        // TODO add your handling code here:
    }//GEN-LAST:event_meItBagiActionPerformed

    private void meItTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItTambahActionPerformed
int Data1 = Integer.parseInt(eData1.getText());  
int Data2 = Integer.parseInt(eData2.getText());  
int Hasil; 
Hasil = Data1+Data2;  // Operasi penjumlahan
eHasil.setText(String.valueOf(Hasil));
        // TODO add your handling code here:
    }//GEN-LAST:event_meItTambahActionPerformed

    private void meItKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meItKurangActionPerformed
int Data1 = Integer.parseInt(eData1.getText());  
int Data2 = Integer.parseInt(eData2.getText());  
int Hasil; 
Hasil = Data1-Data2;  // Operasi pengurangan
eHasil.setText(String.valueOf(Hasil));
        // TODO add your handling code here:
    }//GEN-LAST:event_meItKurangActionPerformed

    private void jMenuPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPersegiPanjangActionPerformed
int panjang = Integer.parseInt(eData1.getText());
    int lebar = Integer.parseInt(eData2.getText());
    
// Hitung luas dan keliling persegi panjang
    int luas = panjang * lebar;
    int keliling = 2 * (panjang + lebar);

eHasil.setText("Luas: " + luas + ", Keliling: " + keliling);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuPersegiPanjangActionPerformed

    private void jMenuSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSegitigaActionPerformed
int alas = Integer.parseInt(eData1.getText());
    int tinggi = Integer.parseInt(eData2.getText());
    
    // Hitung luas dan keliling segitiga (keliling sederhana dengan alas & tinggi)
    double luas = 0.5 * alas * tinggi;
    double keliling = alas + tinggi + Math.sqrt(alas * alas + tinggi * tinggi); // Keliling segitiga siku-siku
    
    // Tampilkan hasil
    eHasil.setText("Luas: " + luas + ", Keliling: " + keliling);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSegitigaActionPerformed

    private void jMenuLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLingkaranActionPerformed
int jariJari = Integer.parseInt(eData1.getText());
    
    // Hitung luas dan keliling lingkaran
    double luas = Math.PI * jariJari * jariJari;
    double keliling = 2 * Math.PI * jariJari;
    
    // Tampilkan hasil
    eHasil.setText("Luas: " + luas + ", Keliling: " + keliling);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuLingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eHasil;
    private javax.swing.JMenu hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuLingkaran;
    private javax.swing.JMenuItem jMenuPersegiPanjang;
    private javax.swing.JMenuItem jMenuSegitiga;
    private javax.swing.JMenuItem meItBagi;
    private javax.swing.JMenu meItBersih;
    private javax.swing.JMenuItem meItKali;
    private javax.swing.JMenuItem meItKurang;
    private javax.swing.JMenuItem meItTambah;
    private javax.swing.JMenu menBantuan;
    private javax.swing.JMenu menFile;
    // End of variables declaration//GEN-END:variables
}
